# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Setting an environment variable with the value of a configuration variable
  env_var: ${{ vars.ENV_CONTEXT_VAR }}

jobs:
  build_and_release:
    runs-on: windows-latest
    name: test
    steps:
      - uses: actions/checkout@v3
      - id: test
        uses:  sanderstad/dacpac-build-and-release@v0.0.12
